baseURL: /
languageCode: en-us
defaultContentLanguage: en
title: Jidin Dinesh
theme: cupper-hugo-theme
googleAnalytics: UA-123456789-1
#disqusShortname: yourdiscussshortname
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: 
  homeMetaContent: Home of Jidin Dinesh.  
  footer: 📧 [Email](mailto:jidin@pm.me)
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: false
  showThemeSwitcher: true
  moveFooterToHeader: true
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js

menu:
  nav:
    - name: Writing
      url: /post/
      weight: 1
    - name: Newsletter
      url: https://getrevue.co/profile/petridish
      weight: 3
    - name: Blog
      url: https://blog.jidin.co
      weight: 2

   # - name: Topics      url: /tags/      weight: 4
   # - name: Twitter      url: https://twitter.com/jidinium      weight: 4
    #- name: RSS url: /index.xml weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 10
    startLevel: 1
