baseURL: 
languageCode: en-us
defaultContentLanguage: en
title: Jidin Dinesh
theme: cupper-hugo-theme
googleAnalytics: 
disqusShortname: 
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  #description: Exploring vs Exploiting 
  homeMetaContent: Ready Player One.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Posts
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
   # - name: Blog
    #  url: https://blog.jidin.xyz/
     # weight: 4
    #- name: About
     # url: /about/
     # weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2

